# This file deploys the components necessary to patch calico and add routes to the host
{{- if .Values.calicoSetup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "CGW.fullname" .}}-calico-setup
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "CGW.fullname" .}}-calico-setup
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "CGW.fullname" .}}-calico-setup
subjects:
- kind: ServiceAccount
  name: {{ template "CGW.fullname" .}}-calico-setup
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ template "CGW.fullname" .}}-calico-setup

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "CGW.fullname" . }}-calico-setup
  namespace: kube-system
  label: 
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "CGW.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "CGW.fullname" .}}-calico-setup
      initContainers:
      - name: {{ .Chart.Name }}-calico-etcd-routing-enabler
        image: "quay.io/coreos/etcd:latest"
        command:
          - /bin/sh
          - "-xc"
          - >
              etcdctl --endpoint=$ENDPOINT set
              calico/bgp/v1/global/custom_filters/v4/ipsec
              "if ( net = $REMOTENET ) then { accept ; }"
        env:
        - name: ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: calico-config
              key: etcd_endpoints
        - name: REMOTENET
          value: "{{ .Values.ipsec.remotenet }}"
      containers:
      - name: {{ .Chart.Name }}-calico-setup
        image: "{{ .Values.calicoSetup.image.repository }}:{{ .Values.calicoSetup.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: IPSEC_SERVICE
          value: {{ template "CGW.fullname" . }}
        - name: IPSEC_REMOTENET
          value: "{{ .Values.ipsec.remotenet }}"
        - name: IPSEC_NAMESPACE
          value: "{{ .Release.Namespace }}"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      hostNetwork: true
   {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
   {{- end }}

{{- end }}
